# @HOST = http://localhost:3000

# ###
# POST {{HOST}}/api/auth/signup
# Content-Type: application/json

# {
#   "email": "cal@gm.com",
#   "password": "12345678",
#   "confirmPassword": "12345678"
# }
# ###

# POST {{HOST}}/api/auth/login
# Content-Type: application/json

# {
#   "email": "clancy@gm.com",
#   "password": "12345678"
# }

# ###

# POST {{HOST}}/api/auth/logout
# Content-Type: application/json
# Authorization: Bearer {{REFRESH_TOKEN}}
# ###



# ###

# GET {{HOST}}/api/user/profile
# Authorization: Bearer {{ACCESS_TOKEN}}

# ###

# POST {{HOST}}/api/auth/refresh-token
# Content-Type: application/json

# {
# }




# ###


# POST {{HOST}}/api/auth/logout
# Authorization: Bearer {{ACCESS_TOKEN}}